"""'first'

Revision ID: 17d9eed59121
Revises: 
Create Date: 2019-04-26 16:08:36.618350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17d9eed59121'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('immediate_group_sending',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('enabled', sa.SMALLINT(), nullable=True, comment='1:功能启用,0:此功能暂停'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('timing_group_sending',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('enabled', sa.SMALLINT(), nullable=True, comment='1:功能启用,0:此功能暂停'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('adv_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('keyword', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword_blacklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('wechat_info',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uin', sa.Integer(), nullable=True, comment='用户唯一标识符'),
    sa.Column('username', sa.String(length=255), nullable=True, comment='用户名称，一个@为好友，两个@为群组'),
    sa.Column('nickname', sa.String(length=255), nullable=True, comment='昵称'),
    sa.Column('headimgurl', sa.String(length=255), nullable=True, comment='头像链接'),
    sa.Column('remarkname', sa.String(length=255), nullable=True, comment='备注名'),
    sa.Column('sex', sa.Integer(), nullable=True, comment='性别，0-未设置（公众号、保密），1-男，2-女'),
    sa.Column('signature', sa.String(length=255), nullable=True),
    sa.Column('admin_user_info_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True, comment='1:登陆;0:未登录'),
    sa.ForeignKeyConstraint(['admin_user_info_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wechat_group',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True, comment='用户名称，一个@为好友，两个@为群组'),
    sa.Column('nickname', sa.String(length=255), nullable=True, comment='昵称'),
    sa.Column('remarkname', sa.String(length=255), nullable=True, comment='备注名'),
    sa.Column('membercount', sa.SMALLINT(), nullable=True, comment='群内人数'),
    sa.Column('isowner', sa.BOOLEAN(), nullable=True, comment='是否群主'),
    sa.Column('time_group_sending_id', sa.Integer(), nullable=True),
    sa.Column('wechat_info_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['time_group_sending_id'], ['timing_group_sending.id'], ),
    sa.ForeignKeyConstraint(['wechat_info_id'], ['wechat_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adv_notification_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('wechat_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['wechat_group_id'], ['wechat_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('auto_reply',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.SMALLINT(), nullable=True, comment='1:定向,0:全部'),
    sa.Column('wechat_group_id', sa.Integer(), nullable=True),
    sa.Column('keyword', sa.String(length=255), nullable=True),
    sa.Column('reply_content', sa.Text(), nullable=True),
    sa.Column('enabled', sa.SMALLINT(), nullable=True, comment='1:功能启用,0:此功能暂停'),
    sa.ForeignKeyConstraint(['wechat_group_id'], ['wechat_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword_notification_group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('wechat_group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['wechat_group_id'], ['wechat_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wechat_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wechat_group_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True, comment='用户名称，一个@为好友，两个@为群组'),
    sa.Column('nickname', sa.String(length=255), nullable=True, comment='昵称'),
    sa.Column('remarkname', sa.String(length=255), nullable=True, comment='备注名'),
    sa.Column('wechat_info_id', sa.Integer(), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['wechat_user.id'], ),
    sa.ForeignKeyConstraint(['wechat_group_id'], ['wechat_group.id'], ),
    sa.ForeignKeyConstraint(['wechat_info_id'], ['wechat_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('welcome_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wechat_group_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.SMALLINT(), nullable=True, comment='1:message,0:pic_content'),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('pic_url', sa.Text(), nullable=True),
    sa.Column('enabled', sa.SMALLINT(), nullable=True, comment='1:功能启用,0:此功能暂停'),
    sa.ForeignKeyConstraint(['wechat_group_id'], ['wechat_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adv_whitelist_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wechat_user_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['wechat_user_id'], ['wechat_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('keyword_whitelist_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wechat_user_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['wechat_user_id'], ['wechat_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('wechat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.Column('wechat_user_id', sa.Integer(), nullable=True),
    sa.Column('wechat_info_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wechat_info_id'], ['wechat_info.id'], ),
    sa.ForeignKeyConstraint(['wechat_user_id'], ['wechat_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorate_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wechat_message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['wechat_message_id'], ['wechat_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorate_message')
    op.drop_table('wechat_message')
    op.drop_table('keyword_whitelist_user')
    op.drop_table('adv_whitelist_user')
    op.drop_table('welcome_info')
    op.drop_table('wechat_user')
    op.drop_table('keyword_notification_group')
    op.drop_table('auto_reply')
    op.drop_table('adv_notification_group')
    op.drop_table('wechat_group')
    op.drop_table('wechat_info')
    op.drop_table('roles_users')
    op.drop_table('keyword_blacklist')
    op.drop_table('adv_blacklist')
    op.drop_table('user')
    op.drop_table('timing_group_sending')
    op.drop_table('role')
    op.drop_table('immediate_group_sending')
    # ### end Alembic commands ###
