"""add groupmembercount

Revision ID: 1c58d2392e81
Revises: 
Create Date: 2019-05-06 11:09:50.872977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c58d2392e81'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_member_count',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('wechat_group_id', sa.Integer(), nullable=True),
    sa.Column('membercount', sa.SMALLINT(), nullable=True),
    sa.Column('createtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['wechat_group_id'], ['wechat_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_member_count')
    # ### end Alembic commands ###
